# Generated by Django 3.2.13 on 2022-11-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('genres', models.TextField()),
                ('poster_url', models.URLField()),
                ('vote_average', models.FloatField()),
                ('release_date', models.TextField()),
            ],
        ),
    ]
