# Generated by Django 3.2.13 on 2022-11-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre_ids',
            field=models.ManyToManyField(related_name='movies', to='movies.Genre'),
        ),
    ]
