# Generated by Django 3.2.13 on 2022-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='community', to='articles.CommunityTag'),
        ),
        migrations.AlterField(
            model_name='foodtag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
