# Generated by Django 3.2.13 on 2022-11-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20221116_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='image_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
